[build]
builder = "NIXPACKS"
buildCommand = "npm install && npm run build"

[deploy]
startCommand = "npm run preview"
restartPolicyType = "ON_FAILURE"
healthcheckPath = "/"
healthcheckTimeout = 200

[service]
ports = [
  { port = 8080, protocol = "http" }
]

[variables]
# Backend URL gets inserted after backend deploy
# VITE_API_URL=""
